name: Build

on:
  push:
    branches: main
    tags:        
      - '*'
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7"]
        # os: [ubuntu-latest, windows-latest, macos-latest]
        # python-version: ["3.7", "3.10"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Install dependencies
        run: |
          python -m pip install -U codecov
          npm install -g codecov
      - name: Test the extension
        run: |
          python -m pip install --upgrade -v -e ".[test, examples, docs]"
          python -m pytest
          yarn run test

      - name: Linting
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          yarn run lint:check

      - name: Check docs can be build + links
        if: ${{ matrix.os == 'ubuntu-latest' }}
        working-directory: docs
        run: |
          sudo apt install -y pandoc
          make html
          python -m pytest --check-links
  deploy:
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - name: Build OMOVI
        run: |
          python -m build .
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}